// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeuCXJm3eaFr1-PTdz26ISskrlFH4yDbo',
    appId: '1:632210147021:web:3ebecc83345719d8d98b84',
    messagingSenderId: '632210147021',
    projectId: 'chat-app-1e26a',
    authDomain: 'chat-app-1e26a.firebaseapp.com',
    storageBucket: 'chat-app-1e26a.firebasestorage.app',
    measurementId: 'G-GG6CPFQQQD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByf4MkIzpCc8VSDj_j0HfkKzJxS4FuRHs',
    appId: '1:632210147021:android:ace7a8aae71d4322d98b84',
    messagingSenderId: '632210147021',
    projectId: 'chat-app-1e26a',
    storageBucket: 'chat-app-1e26a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOsLCmL_O8gO32XptViAG3rvLhqNAwdMM',
    appId: '1:632210147021:ios:57fdf0d234217ea4d98b84',
    messagingSenderId: '632210147021',
    projectId: 'chat-app-1e26a',
    storageBucket: 'chat-app-1e26a.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOsLCmL_O8gO32XptViAG3rvLhqNAwdMM',
    appId: '1:632210147021:ios:57fdf0d234217ea4d98b84',
    messagingSenderId: '632210147021',
    projectId: 'chat-app-1e26a',
    storageBucket: 'chat-app-1e26a.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeuCXJm3eaFr1-PTdz26ISskrlFH4yDbo',
    appId: '1:632210147021:web:51c43368eec68966d98b84',
    messagingSenderId: '632210147021',
    projectId: 'chat-app-1e26a',
    authDomain: 'chat-app-1e26a.firebaseapp.com',
    storageBucket: 'chat-app-1e26a.firebasestorage.app',
    measurementId: 'G-55XXMJPDH4',
  );
}
